#!/usr/bin/env python3
"""build_index.py — regenerate the static root index.html.

Scans profiles/*/ for a dashboard.html plus its dashboard-meta.json sidecar and
writes a static index.html at the repo root linking every profile that has
produced a dashboard. Pure templated output from data already on disk — there is
NO client-side script that reads the filesystem at view-time, so the page works
opened directly from file://.

dashboard-meta.json schema:
  {"profile": str, "last_run": str, "counts": {..}, "status_line": str}

Usage:
  python3 skill/lib/build_index.py [--root .]
"""
import os
import sys
import json
import html
import argparse

DEFAULT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Job searches · index</title>
<style>
  :root{{--ink:#1b2725;--paper:#e8ede9;--card:#fbfcfb;--muted:#5c6661;
    --rule:#d4dbd5;--estuary:#2f6f6b;}}
  *{{box-sizing:border-box;}}
  body{{margin:0;background:var(--paper);color:var(--ink);
    font-family:"Inter",system-ui,sans-serif;line-height:1.5;padding:0 0 64px;}}
  .wrap{{max-width:820px;margin:0 auto;padding:0 20px;}}
  header{{padding:44px 0 8px;}}
  h1{{font-family:"Spectral",Georgia,serif;font-weight:600;font-size:34px;margin:0 0 6px;}}
  .sub{{color:var(--muted);font-size:14px;margin:0;}}
  .card{{display:block;text-decoration:none;color:inherit;background:var(--card);
    border:1px solid var(--rule);border-radius:12px;padding:18px 20px;margin:16px 0;}}
  .card:hover{{box-shadow:0 4px 22px -14px rgba(27,39,37,.4);}}
  .name{{font-weight:600;font-size:18px;margin:0 0 2px;}}
  .meta{{font-family:"Space Mono",ui-monospace,monospace;font-size:12px;color:var(--muted);margin:0 0 8px;}}
  .counts{{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 8px;}}
  .pill{{font-family:"Space Mono",ui-monospace,monospace;font-size:11px;
    background:#e3eeec;color:var(--estuary);border-radius:6px;padding:3px 8px;}}
  .status{{font-size:13.5px;color:var(--ink);margin:0;}}
  .empty{{color:var(--muted);font-size:14px;margin:24px 0;}}
  footer{{margin-top:40px;padding-top:18px;border-top:1px solid var(--rule);
    font-size:12.5px;color:var(--muted);}}
</style>
</head>
<body>
<div class="wrap">
<header>
  <h1>Job searches</h1>
  <p class="sub">{count} search{plural} with a current dashboard. Static index — open any card from disk.</p>
</header>
{cards}
<footer>Generated by build_index.py from each profile's dashboard-meta.json. No live data is read at view-time.</footer>
</div>
</body>
</html>
"""

CARD = """<a class="card" href="{href}">
  <p class="name">{name}</p>
  <p class="meta">last run: {last_run}</p>
  <div class="counts">{pills}</div>
  <p class="status">{status}</p>
</a>"""


def esc(v):
    return html.escape(str(v)) if v is not None else ""


def main():
    ap = argparse.ArgumentParser(description="Regenerate the static root index.html.")
    ap.add_argument("--root", default=DEFAULT_ROOT, help="repo root (default: inferred)")
    args = ap.parse_args()

    profiles_dir = os.path.join(args.root, "profiles")
    cards = []
    for name in sorted(os.listdir(profiles_dir)) if os.path.isdir(profiles_dir) else []:
        pdir = os.path.join(profiles_dir, name)
        dash = os.path.join(pdir, "dashboard.html")
        meta_path = os.path.join(pdir, "dashboard-meta.json")
        if not (os.path.exists(dash) and os.path.exists(meta_path)):
            continue
        try:
            meta = json.loads(open(meta_path, encoding="utf-8").read())
        except (ValueError, OSError) as exc:
            print(f"build_index.py: skipping {name} — bad meta ({exc})", file=sys.stderr)
            continue
        counts = meta.get("counts", {}) or {}
        pills = "".join(
            f'<span class="pill">{esc(k)}: {esc(v)}</span>' for k, v in counts.items()
        )
        cards.append(CARD.format(
            href=esc(f"profiles/{name}/dashboard.html"),
            name=esc(meta.get("profile", name)),
            last_run=esc(meta.get("last_run", "—")),
            pills=pills,
            status=esc(meta.get("status_line", "")),
        ))

    body = "\n".join(cards) if cards else '<p class="empty">No dashboards yet. Run a search to produce one.</p>'
    page = PAGE.format(
        count=len(cards),
        plural="" if len(cards) == 1 else "es",
        cards=body,
    )
    out_path = os.path.join(args.root, "index.html")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(page)
    print(f"build_index.py: indexed {len(cards)} dashboard(s) -> {out_path}", file=sys.stderr)
    print(out_path)


if __name__ == "__main__":
    main()
